name:      Tool
about:     Issue for managing an individual tool
title:     "[TOOL]"
labels:    ["\U0001F6E0ï¸ tool"]
assignees: ''
body:

  - type: textarea
    attributes:
      description: What problem does the suggested tool solve?
      label:       Describe the problem

  - type: textarea
    attributes:
      description: What features should the suggested tool have?
      label:       Features
      value: |
        - [ ] feature
        - [ ] feature

  - type: markdown
    attributes:
      value: |
        - [ ] Purpose/Overview
        - [ ] Directions, hidden once dismissed
        - [ ] Underlying libraries, with links
        - [ ] Save work + settings to local storage
        - [ ] Domain redirects (e.g. `transliterate.digitallinguistics.io` > `tools.digitallinguistics.io/transliterate`
        - [ ] Data Import/Export
          - [ ] copy-paste
          - [ ] file upload/download
          - [ ] cloud services
        - [ ] Update issue templates to include the tool as an option."