name:        Tool
description: Issue for managing an individual tool
title:       "[TOOL]"
labels:      ["\U0001F6E0️ tool"]
assignees:   []
body:

  - type: textarea
    attributes:
      description: What problem does the suggested tool solve?
      label:       Describe the problem

  - type: textarea
    attributes:
      description: What features should the suggested tool have?
      label:       Features
      value: |
        - [ ] feature
        - [ ] feature